### ISSUE TITLE
[Feature Request] iostat mit aufnehmen

### ISSUE THREAD

**Issue by Hypnos3** [fhetty/hm-tools#10]
Hallo,

vielleicht wäre es möglich iostat mit in das Paket aufzunehmen?

Wie [hier](https://homematic-forum.de/forum/viewtopic.php?f=26&t=55151&start=10#p549013) von Jens vorgeschlagen.

Danke & Gruß

**Comment by fhetty** [comment]
Hi,
merke ich mir für das nächste Update vor.
Ich hoffe, das ich über die Feiertage dazu komme.

Gruß
Frank

**Comment by fhetty** [comment]
Erledigt!
