### ISSUE TITLE
Funktioniert das addon auch mit RPI4 ?

### ISSUE THREAD

**Issue by roe1974** [fhetty/hm-tools#11]
Wie oben beschrieben ... mit RPI4 auch kompatible ?

lg Richard

**Comment by Hypnos3** [comment]
Ich habe es auch auf einem Pi4 installiert und bisher keine Probleme festgestellt.

**Comment by fhetty** [comment]
Ja, hatte es auf meinem Raspi4. Ohne Probleme!

**Comment by roe1974** [comment]
danke !
