### ISSUE TITLE
[Feature Request] tmux

### ISSUE THREAD

**Issue by esodevel** [fhetty/hm-tools#12]
Danke für dieses Add-on, die Tools haben mir gefehlt. Ein Ergänzungsvorschlag noch wäre tmux, dann würde man in vielen Fällen mit einer Shell auskommen.

**Comment by fhetty** [comment]
Mache tmux als eigenes addon! Ich muss auf UTF-8 umstellen, da tmux sonst nicht läuft!
Sollte morgen fertig sein. Zu finden unter fhetty/hm-tmux.

**Comment by fhetty** [comment]
So, hier zum ausprobieren:)
https://github.com/fhetty/hm-tmux/releases

**Comment by esodevel** [comment]
Wenn nur tmux mit UTF-8 läuft, alles andere aber mit ISO, dann hilft das irgendwie nicht so richtig - ich würde gerne mc, nano, htop etc. mit tmux nützen können. Wäre es nicht sinnvoller, generell auf UTF-8 umzustellen? Das ist ja mittlerweile Standard.

**Comment by fhetty** [comment]
Hi, das macht das Addon, wenn du es installierst!
Das System wird auf UTF-8 umgestellt.
Wenn Putty auf UTF-8 eingestellt ist, wird alles richtig anzeigt, auch die hm-tools!
Bei mir hat alles ohne Probleme funktioniert. (nano, mc ...)

**Comment by esodevel** [comment]
Stimmt, funktioniert wunderbar. Sieht gut aus soweit.

**Comment by fhetty** [comment]
Hi,
wenn du probleme mit tmux (UTF-8) bekommen solltest, einfach im hm-tmux repositorie melden.
