### ISSUE TITLE
Add oathtool for MFA

### ISSUE THREAD

**Issue by Andi097** [fhetty/hm-tools#13]
Would you please add oathtool. Would be very useful to work with MFA.

Thanks in advance

**Comment by fhetty** [comment]
What do you need?
Arm or x86?

**Comment by Andi097** [comment]
ARM for the Rasperrymatic.

Thank you!

**Comment by fhetty** [comment]
OK!
Can you test the binary for me?
I currently have no arm system in use!
Copy the file "oathtool" from the folder "test" to the Raspi.
Path = /usr/local/addons/hm-tools/bin
Set the file rights to 755 and let me know if the program works!
Thank you

**Comment by fhetty** [comment]
Sorry!
I forgot the lib's.
Copy to /usr/local/addons/hm-tools/lib
Thank you!

**Comment by Andi097** [comment]
Thank you!

It shows the following error:
/usr/local/addons/hm-tools/bin/oathtool: error while loading shared libraries: liboath.so.0: cannot open shared object file: No such file or directory

I gave the lib files the same rights (755)

**Comment by fhetty** [comment]
Did you copy the libs from test/lib?
/usr/local/addons/hm-tools/lib
If it doesn't work, reboot the Raspi!
Please report if it doesn't work!

**Comment by fhetty** [comment]
Sorry!
Updated the Libs!
Copy the tar.gz to the Raspi
Extract the file to /usr/local/addons/hm-tools/lib
I did it with mc and putty!

**Comment by Andi097** [comment]
Hi, 
it works with the new lib files but=> I had to put them in the same dir as oathtool.

when it was in the lib directory i got the same error as usual. so everything is now in 
/usr/local/addons/hm-tools/bin

Thank you so much for your fast help!!!

**Comment by fhetty** [comment]
Hi,
in my Raspi test system it works with "/usr/local/addons/hm-tools/lib".
I will integrate this feature soon in the hm-tools!
If you have any problems, just report again!

**Comment by fhetty** [comment]
Built-in!
