### ISSUE TITLE
Glances – Linux System Monitoring Tool

### ISSUE THREAD

**Issue by tempo3** [fhetty/hm-tools#14]
Hello, it would be great if its possible in future to use the Linux system monitoring tool "Glances" on the Raspimatic. I have not found any option as of today. Thank you in advance for the support.

**Comment by fhetty** [comment]
Ok, i build in the next version!
x86 or arm?

**Comment by tempo3** [comment]
Great! Raspberry ARM.

**Comment by fhetty** [comment]
Glances is python!
I have to create a python addon first for Glances to work!
Give me some time!
