### ISSUE TITLE
HM-Tools on Raspberry 1 B+

### ISSUE THREAD

**Issue by JoeHaenf** [fhetty/hm-tools#17]
Hallo,
Ich möchte hm-tools auf einem Raspberry Pi 1 B+ laufen lassen. 
Wenn ich bash ausführe, erhalte ich die Fehlermeldung "illegal instruction". Liegt das vielleicht daran, dass der 1er Raspberry ARMv6 ist?
Gibt es eine Möglichkeit, dies auf einer Raspi 1 zum Laufen zu bringen?

**Comment by fhetty** [comment]
Hi,
die Tools laufen nicht auf RaspberryPi Zero und allen anderen Raspis, die vom System her  RaspberryMatic-..........rpi0.zip verwenden.
Da ich keins der Systeme habe, müsste ich ins blaue kompilieren, ohne zu testen.
Tut mir leid!

**Comment by robbyHuelsi** [comment]
Schade, hätte mich auch interessiert.

**Comment by klour** [comment]
In der Tat schade. Hätte auch Interesse. Betreibe ebenfalls Raspberrymatic sehr stabil und erfolgreich auf einem Raspberry Pi 1B (ohne +), also auch mit dem rpi0-image. Wird sicherlich noch eine Weile dauern, bis der Pi 1B bei mir einem neueren Modell weicht.

Die tools nano, htop und midnight commander und iostat wären direkt auf dem System schon eine Bereicherung. Filesystem-relevantes kann man sicherlich auch mit anderen Mitteln (bspw. WinSCP) von einem entfernten Rechner erledigen. Aber htop und iostat machen eigentlich nur direkt auf dem Pi-System Sinn.

htop direkt auf dem Pi wäre schon deutlich komfortabler und übersichtlicher als top.
vi hingegen ist ein echter Krampf, aber das ist natürlich Geschmacksache. nano wäre hier ein echter Segen.
