### ISSUE TITLE
only mc is running

### ISSUE THREAD

**Issue by 303acid** [fhetty/hm-tools#18]
hi,

ssh into ccu3...
id
uid=0(root) gid=0(root)
htop
htop: /lib/libc.so.6: version `GLIBC_2.28' not found (required by htop)

expect
expect: /lib/libm.so.6: version `GLIBC_2.29' not found (required by /usr/local/addons/hm-tools/lib/expect5.45.4/libexpect5.45.4.so)
expect: /lib/libc.so.6: version `GLIBC_2.28' not found (required by /usr/local/addons/hm-tools/lib/expect5.45.4/libexpect5.45.4.so)
expect: /lib/libm.so.6: version `GLIBC_2.29' not found (required by /usr/local/addons/hm-tools/lib/libtcl8.6.so)
expect: /lib/libc.so.6: version `GLIBC_2.28' not found (required by /usr/local/addons/hm-tools/lib/libtcl8.6.so)

bash
bash: error while loading shared libraries: libreadline.so.8: cannot open shared object file: No such file or directory
bash: error while loading shared libraries: libreadline.so.8: cannot open shared object file: No such file or directory

nano
nano: /lib/libc.so.6: version `GLIBC_2.28' not found (required by nano)

mc and iostat are running...! any ideas? GLIBC on CCU3 is 2.27

**Comment by fhetty** [comment]
hi,
use you the original ccu3 firmware?

**Comment by fhetty** [comment]
have you restarted the system after installing the hm-tools?

**Comment by 303acid** [comment]
YES, i think so. no modification from my side. Firmware is 3.61.5 currently

Am Sa., 18. Dez. 2021 um 07:03 Uhr schrieb fhetty ***@***.***

**Comment by fhetty** [comment]
library path is not correct or loaded!
is hm-tools-addons.sh in /usr/local/etc/profile.d
if so, just do the following in the terminal:
/usr/local/etc/profile.d/hm-tools-addons.sh
then test again hm-tools
sorry,
i have never tested the hm-tools under ccu3 original firmware!

**Comment by 303acid** [comment]
sry. it's not working. always GLIBC_2.28 not found.
i have tryed some symlinks to the 2.27 Version but no success

Am Sa., 18. Dez. 2021 um 10:19 Uhr schrieb fhetty ***@***.***

**Comment by fhetty** [comment]
hmmmmm...
the hm-tools are not released from me for the CCU3, since I have no CCU3 for testing!
the hm-tools are compiled for homematic-raspi.
the bin's are probably not compatible with the system (original ccu3)
sorry!
