### ISSUE TITLE
midnight commander funktioniert nicht mehr

### ISSUE THREAD

**Issue by Schastar** [fhetty/hm-tools#21]
In der neuen RaspberryMatic 3.69.7.20230626 bekomme ich die folgende Fehlermeldung, wenn ich den mc starten will:
mc: error while loading shared libraries: libpcre.so.1: wrong ELF class: ELFCLASS64

**Comment by fhetty** [comment]
Hi,
Frage1: Welche Hardware hast du?
Frage2: Ist das System neu aufgesetzt, oder besteht das Problem erst nach einem System-Update?
Bitte soviel Infos wie möglich!

**Comment by Schastar** [comment]
Hallo,
Ich nutze einen RaspberryPi 3 mit einer SSD über USB angeschlossen.
Das Problem trat nach dem System-Update auf die neue Version auf.
Als Zusatzsoftware nutze ich noch: CUx-Deamon, CCU-Historian und hm-pdetect.

**Comment by fhetty** [comment]
Hi, sollte eigentlich funktionieren!
Den Raspi schonmal neu gestartet?
Wenn das nicht funktioniert, hm-tools nochmal aufspielen, und danach den Raspi neu starten.
Wenn das nichts bringt, einfach nochmal melden!
Dann muss ich mir einen Raspi3 organisieren, um das Problem nachvollziehen zu können!
Auf meinem Rpi4 läuft es!

**Comment by Schastar** [comment]
Hi,
Ich hab sicherheitshalber mal die SSD geclont, die komplette Zusatzsoftware deinstalliert, neugestartet und hm-tools wieder installiert.
Ich benutze übrigens den HmIP-RFUSB und eine PiFace Shim RTC.
Die RTC habe ich dann auch noch entfernt.

Leider alles ohne Erfolg. Ich bekomme immernoch diese Fehlermeldung.

Wegen mir musst du dir keinen Raspi3 kaufen oder so, dann nutze ich halt wieder die normalen Kommandos (der mc war halt praktisch) .
Vielleicht behebt sich das Problem auch mit einem der nächsten Raspberrymatic-Updates.
Oder dir fällt nochwas ein, wie gesagt ich habe die SSD geclont und kann rumprobieren...

**Comment by fhetty** [comment]
Hi
Ich schau mal, ob ich das Problem irgendwie nachvollziehen kann.
Bei mir läuft das Ganze auf einem Tinkerboard.
Notfalls aktualisiere ich mal alle Tools und libs.
Hatte ich sowieso vor!
Ich muss jetzt nur noch die Kurve dafür bekommen!
Kann aber etwas dauern!
Aber ich bleibe dran!

**Comment by fhetty** [comment]
Hi,
konnte den Fehler mit einem Rpi3 nachvollziehen
Gibt die Tage eine neue Version (0.7.0)
Dauert nur etwas, da ich zz alles in einer Linux-VM mache!
Hat nichts mit deiner Soft oder Hardware zu tun :-)
Der Fehler kommt auch bei einem frisch aufgesetzten System!

**Comment by fhetty** [comment]
So,
sollte jetzt wieder funktionieren!
Bitte um Rückmeldung :-)

**Comment by fhetty** [comment]
Info!
es kann sein, das die Tools erst beim zweiten Öffnen des SSH Terminals funktionieren!
Ein Neustart war bei mir nie erforderlich!
Habe auf Rasp4, Tinkerboard, und x86 System getestet!

**Comment by Schastar** [comment]
Hab deine neue Version installiert und hat direkt beim ersten Öffnen funktioniert.
Supi!
Viiielen Dank

**Comment by fhetty** [comment]
OK!
Danke für die Rückmeldung!
