### ISSUE TITLE
Bash funktioniert leider nicht

### ISSUE THREAD

**Issue by superpower10** [fhetty/hm-tools#5]
bash funktioniert leider nicht.

Es kommt folgende Fehlermeldung:
bash: error while loading shared libraries: libreadline.so.7: cannot open shared object file: No such file or directory

**Comment by superpower10** [comment]
Nachdem ich symlinks für libreadline.so.7 und libhistory.so.7 ins add-on lib-Verzeichnis erstellt habe, kann ich bash abschicken und es kommt keine Fehlermeldung.
Allerdings geht es trotzdem nicht

**Comment by fhetty** [comment]
OK, ich kümmere mich um das Problem!
Werde dann eine aktualisierte Version online stellen.

**Comment by fhetty** [comment]
Bash sollte jetzt funktionieren.
Bitte testen, und bei Problemen nochmal melden!
