### ISSUE TITLE
Request: Python 3

### ISSUE THREAD

**Issue by Tscherno** [fhetty/hm-tools#6]
Python3 wäre für mich (und sicher auch für andere) sehr hilfreich.

**Comment by Hypnos3** [comment]
Das wäre besser als eigenes AddOn aufgehoben.

**Comment by fhetty** [comment]
Hi,
schaue ich mir an, aber vermutlich wirklich besser in einem eigenen Addon aufgehoben.
Ich hoffe, das ich dieses Wochenende ein wenig Zeit finde.
Melde mich wieder.

Gruß
Frank

**Comment by fhetty** [comment]
Hi,
habe mal im Buildroot Python3 eingebunden.
Wird von der Größe ca. 14MB.
Wenn interesse besteht, werde ich ein eigenes Addon daraus machen.
Bläst mir sonst die hm-tools zu weit auf. 
Einfach bescheid geben.

**Comment by Tscherno** [comment]
Wäre super. Wenn Du es nicht in hm-tools integrieren willst, kein Problem mit eigenem Addon. Mir würde es gerade wahnsinnig helfen, da es für Pyhthon ein Script gibt um meine Wohnraumlüfter zu steuern. Kriege ich mit Node-Red nicht so schön hin.

**Comment by Hypnos3** [comment]
Es gibt ein Projekt pmatic [forum](https://homematic-forum.de/forum/viewtopic.php?t=29509#p265217) / [webseite](https://larsmichelsen.github.io/pmatic/doc/index.html), wo es um Python für die CCU geht. Leider gab es da scheinbar seit längerem keine Weiterentwicklung. Es gibt aber auch aktuellere Pull-Requeste für Python3. Vielleicht gibt es auch einen aktuellen Fork.

@Tscherno: Wenn du das Script mal bereitstellen würdest, könnte ich versuchen es auf Node-Red umzustellen.

**Comment by Tscherno** [comment]
@Hypnos3 Das wäre natürlich der Oberhammer. Das Script gibts sogar bei Github:
https://github.com/aglehmann/pyEcovent

**Comment by Tscherno** [comment]
Eigentlich ist es ziemlich trivial - UDP Telegram schicken und man tut was bzw. empfängt die Daten. Problem habe ich hauptsächlich mit dem Toggeln. Man kann leider nicht bewusst ein oder ausschalten sondern toggelt nur. Das heisst man muss kurz vorher abfragen und dann entsprechend schicken oder nicht. Das schaffe ich mit node red nicht vernünftig. Ideal wäre ein eigenes Paket welches das kapselt.

**Comment by fhetty** [comment]
Moin nochmal!
Läuft es jetzt mit pmatic, oder soll ich mich mal an python3 Addon versuchen???
Ich habe mit python noch nicht gearbeitet, und brauche dann auf jeden Fall Beta-Tester!

Gruß
Frank

**Comment by Tscherno** [comment]
Äh pmatic ist anders rum. Python API um Homematic zu steuern. Ich brauche python3 runtime auf der Homematic.

**Comment by Hypnos3** [comment]
Laut Beschreibung ist es möglich mit pmatic scripte auf der CCU auszuführen. Ich habe das aber nie probiert. 

Wenn du jetzt nur die Runtime hast, wie bekommst du dann die Verbindung zum Rest der HomeMatic?

In NodeRed gibt es die function Nodes. Damit kann man so ein toggeln hinbekommen. Ist halt dann nur JavaScript anstelle Python.

**Comment by Tscherno** [comment]
Ich würde das Script per Node-Red mit entsprechenden Parametern starten. Function node ist schon klar, aber das ganze ist Asynchron und ich habe auch mehrere Geräte die alle auf dem selben Port zurückmelden. Das ist zeitlich nicht so toll. Ich hoffe, dass man das mit einem synchron arbeitenden Script besser hinbekommt.

Installation von pmatic hat leider kein verwendbares python hinterlassen...
# python
/usr/local/bin/python: line 9: python2.7: not found
# /usr/bin/python
-sh: /usr/bin/python: not found
