### ISSUE TITLE
Illegal instruction

### ISSUE THREAD

**Issue by ghost** [fhetty/hm-tools#7]
Habe das aktuelle Paket in der Raspberrymatic 3.45.7.20190511 installiert. Wird auch als Version 0.4.6 angezeigt.
Es kommt bei jeder Anwendung die ich starten möchte 

"Illegal instruction"

gruß Uli

**Comment by fhetty** [comment]
Hi,
gib mir bitte mal mehr Details!
Dann kann ich das hoffentlich Problem einfacher lokalisieren!

Gruß
Frank

**Comment by ghost** [comment]
Es gibt leider keine Logeinträge die hier weiterhelfen könnten. Ich verwende das Image RaspberryMatic-3.45.7.20190511-rpi0.zip für den Raspberry Pi Zero W. Die Fehlermeldungen kommen auf der Shell. Selbst die bash lässt sich nicht starten. Immer kommen folgende Fehler:

mc
Illegal instruction
bash
Illegal instruction
mcedit
Illegal instruction

Selbst wenn ich in das Verzeichnis direkt gehe.

Danke
Uli

**Comment by fhetty** [comment]
Hi,
das ist schlecht!
Ich verwende auch dieses Image, aber auf dem Tinkerboard!
Einen Raspi Zero W habe ich nicht, nur noch einen Raspi 3!
Mit dem Tinker scheint alles zu laufen.
Werde die Tage nochmal den Raspi 3 probieren.
Gehe aber davon aus, das der auch funktioniert.
Ich schaue mal, was ich herausfinde.
Haben die hm-tools schonmal auf dem Zero W funktioniert?

Gruß
Frank

**Comment by ghost** [comment]
Hallo Frank,

nein leider noch nicht. Habe bis jetzt das Thema Homematic im Fhem mit einem CUL-Stick und der TCUL Firmware verwendet. Da es jedoch mehrere Probleme damit gibt, möchte ich auf eine CCU in Form von Raspberrymatic umziehen. Was für Addons hast Du in Verwendung? Eventuell gibt es Abhängigkeiten die einen Einfluss haben.

Gruß
Uli

**Comment by fhetty** [comment]
Hi Uli,
eigentlich haben die hm-tools nichts mit der Homematic-Raspi zu tun.
Die Tools greifen auf das Buildroot System zu, auf der auch die Homematic-Raspi Software läuft.
Hast du nicht zufällig einen Raspi 2 oder 3 zur Hand, um damit einmal dein System zu testen?
Ich bin damals sogar auf des Tinkerboard gewechselt, um noch bessere Performance zu haben.
Die hm-tools laufen ohne jegliche zusätzliche Addons!
Aber hier mal meine verwendeten Addons:
Programmedrucken
XML-API
CUx-Daemon
E-Mail
Script-Parser
HM-Tools (natuerlich) :)

Gruß
Frank

**Comment by ghost** [comment]
Hi Frank,
alles installiert, jedoch keinen Erfolg. Jetzt ist der ganze Screen mit Addons vollgepackt. Für mich ist der Pi Zero W das Teil womit ich das Projekt realisiern möchte. Die Installation hat bei mir über den Umweg eines USB-LAN Adapters funktioniert. Einrichtung mit Tastatur und Monitor wollte nicht. Habe mir hierzu extra einen HDMI Adapter besorgt. Die USB Tastatur wollte nicht, so dass ich es mit besagtem Adapter eingerichtet habe. Es läuft jetzt auch, wobei der LAN Adapter am USB bleiben muss. Die Verbindung ins Netz erfolgt per WLAN. Alles bis auf dein Addon läuft ohne Probleme. Na ja, im schlimmsten Fall muss ich ohne meinen geliebten Midnight Commander leben. Einen Pi 2 oder 3 habe ich nicht zur Verfügung. Mein Fhem läuft auf einem Odroid XU4. Da er hiermit unterfordert ist habe ich unter anderem eine Owncloud mit eigener USB3 - 2TB HDD. Für den Bootvorgang verwende ich eine SD-Karte, und dann läuft alles auf eine kleinen SSD, die ebenfalls am USB3 hängt. 
Bei der Homematic Geschichte habe ich bis jetzt einen CUL-Stick verwendet. Auch werden unterschiedliche Systeme in Fhem integriert, wie Mysensors, TRX-Com, FS20, MAX!, Lacrosse. Die Homematic gefällt mir bezüglich der Sicherheit. Das einzige was bei mir wieder beendet wurde, ist das Zigbee Teil. Das hat mir soviel Systemlast verursacht, dass die Homematic komplett wegen Timingproblemen ausgefallen ist. Da werde ich nach dem Umstieg auf das Raspberrymatic nochmal ran gehen. Linux ist für mich jetzt auch nicht gerade ein Problem. Nur diese Buildroot und Busybox Sache ist für mich ehrlich gesagt wilde Bastelei. Da hängt das ganze System kreuz und quer mit Links zusammen. 
Danke trotzdem für deine Mühe.

Gruß 
Uli

**Comment by fhetty** [comment]
Hi Uli,
schick mir mal bitte ein PN aus dem homematic-forum.de.
Mein User Name ist hetty.
Dann können wir direkt über Mail kommunizieren.

Gruß
Frank

**Comment by weissjuergen** [comment]
Hi, wurde das Problem auf dem Pi Zero inzwischen gelöst, ich bekomme mit den HMTools auch Fehlermeldung „illegal instruction“ ?

**Comment by fhetty** [comment]
Hi
Nein, leider nicht!
Da ich keinen Pi Zero habe kann ich das Problem nicht nachvollziehen.
Aus diesem Grund habe ich auch in die Readme geschrieben, das die HM-Tools
nur unter folgenden Systemen getestet sind:
Raspi2, Raspi3, Raspi4, Synology NAS (x86 "ova")
