### ISSUE TITLE
SSHPASS

### ISSUE THREAD

**Issue by WolfHenk** [fhetty/hm-tools#8]
Ich hätte den Vorschlag, SSHPASS in diese Sammlung aufzunehmen. 
Damit kann dann ein Sortiment SSH-Befehle ohne umständliches Gewese mit Keys usw. auf anderen Maschinen ausgeführt werden.

**Comment by fhetty** [comment]
Sorry, das ich mich jetzt erst melde!
Habe es in der neusten Version eingebaut.
Bitte testen!
