### ISSUE TITLE
Unterstützung für neue x86-basierte RaspberryMatic Version

### ISSUE THREAD

**Issue by jens-maus** [fhetty/hm-tools#9]
Mit der nächsten kommenden RaspberryMatic version wird es eine neue zusätzlich Plattform für RaspberryMatic geben. Dabei handelt es sich um eine x86 (i686) basierte Version die als erste Iteration für das erzeugen einer virtuellen RaspberryMatic unter Virtualisierungsumgebungen (sog. "ova" platform) herausgebracht wird.

Da die Binaries im hm-tools Addon momentan lediglich ARM-basierte Binaries sind funktioniert dieses Addon momentan leider nicht mit der neuen "ova" Plattform. Es wäre daher schön wenn das Addon entsprechend um diese zusätzlich Plattform erweitert werden könnte und binaries mit ausgeliefert werden die auf einem i686/x86 System lauffähig sind.

Mehr Information zur neuen "ova" Plattform findet man momentan hier:
https://homematic-forum.de/forum/viewtopic.php?f=65&t=54055#p538104

**Comment by fhetty** [comment]
Ist in Arbeit!

**Comment by fhetty** [comment]
So, habe lange überlegt, ob ich für x86 eine eigene Version mache.
Habe mich dann aber für diese Lösung entschieden.
Alles in einem addon, und das Update-Script entscheidet, welche Binarys kopiert werden.
Testes es mal durch!
Bei mir funktioniert es bestens.
Habe die Tools auf die neuste Version gebracht, und hoffe, das alle funktionieren.
Bei Problemen einfach melden.

**Comment by jens-maus** [comment]
Wunderbar und gute Idee das du dich dafür entscheiden hast das alles in ein .tar.gz zu machen. So hätte ich das auch vorgeschlagen weil ich das auch für andere addons so bereits umgesetzt habe. Das ergibt mehr sinn als separate archive die die nutzer nur wieder durcheinander bringen.
